

services:
  backend:
    build: .
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env.prod
    ports:
      - "8000:8000"
    volumes:
      - ./media:/app/media
      - static_data:/app/static
    command: >
      sh -c "python manage.py migrate &&
          python manage.py collectstatic --noinput &&
          gunicorn config.wsgi:application --bind 0.0.0.0:8000"

  database:
    image: postgres:17.5
    restart: always
    env_file:
      - .env.prod
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./media:/app/media
      - static_data:/app/static

volumes:
  postgres_data:
  static_data:
