# Generated by Django 5.1.7 on 2025-03-18 16:01

import core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to='course-images/')),
                ('intro', models.FileField(upload_to='course-intro-videos/', validators=[core.validators.validate_video_file])),
                ('price', models.IntegerField()),
            ],
        ),
    ]
