# Generated by Django 5.1.7 on 2025-04-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_course_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='video',
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='level',
            name='image',
            field=models.ImageField(default='', upload_to='level-images/', verbose_name='Level Image'),
            preserve_default=False,
        ),
    ]
