# Generated by Django 5.1.7 on 2025-04-27 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_lesson_video_lesson_video_url_level_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='selected_answer',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='user',
        ),
        migrations.DeleteModel(
            name='QuizAnswer',
        ),
        migrations.DeleteModel(
            name='QuizQuestion',
        ),
        migrations.DeleteModel(
            name='UserAnswer',
        ),
    ]
