# Generated by Django 5.1.7 on 2025-04-30 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_useranswer_selected_answer_and_more'),
        ('quiz', '0004_useranswer_is_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizs', to='core.lesson'),
        ),
    ]
