# Generated by Django 5.1.7 on 2025-05-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_quiz_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='xp',
            field=models.IntegerField(default=0),
        ),
    ]
